export const GRAMMAR_CASE_QUESTIONS = [
  { id:'nom-m-def', caseNumber:1, caseLabel:'1격 · Nominativ(주격)', sentence:'___ Mann ist mein Lehrer.', choices:['der','den','dem','des'], answer:'der', translation:'그 남자는 나의 선생님이다.', explanation:'Mann이 문장의 주어이므로 1격이에요. 남성 정관사 1격은 der예요.' },
  { id:'nom-f-def', caseNumber:1, caseLabel:'1격 · Nominativ(주격)', sentence:'___ Frau kommt aus Köln.', choices:['die','der','den','das'], answer:'die', translation:'그 여자는 쾰른에서 온다.', explanation:'Frau가 행동하는 주어이므로 1격이에요. 여성 정관사 1격은 die예요.' },
  { id:'nom-n-def', caseNumber:1, caseLabel:'1격 · Nominativ(주격)', sentence:'___ Kind spielt im Garten.', choices:['das','dem','des','den'], answer:'das', translation:'그 아이는 정원에서 논다.', explanation:'Kind가 행동하는 주어이므로 1격이에요. 중성 정관사 1격은 das예요.' },
  { id:'nom-pl-def', caseNumber:1, caseLabel:'1격 · Nominativ(주격)', sentence:'___ Kinder lernen Deutsch.', choices:['die','den','der','das'], answer:'die', translation:'그 아이들은 독일어를 배운다.', explanation:'Kinder가 문장의 주어예요. 복수 정관사 1격은 die예요.' },
  { id:'nom-m-indef', caseNumber:1, caseLabel:'1격 · Nominativ(주격)', sentence:'Das ist ___ Freund von Anna.', choices:['ein','einen','einem','eines'], answer:'ein', translation:'이 사람은 안나의 친구 한 명이다.', explanation:'sein 뒤에서 주어를 설명하는 Freund도 1격이에요. 남성 부정관사 1격은 ein이에요.' },
  { id:'nom-f-indef', caseNumber:1, caseLabel:'1격 · Nominativ(주격)', sentence:'Sie ist ___ Lehrerin.', choices:['eine','einer','einen','einem'], answer:'eine', translation:'그녀는 선생님이다.', explanation:'sein 뒤에서 주어를 설명하는 Lehrerin은 1격이에요. 여성 부정관사 1격은 eine예요.' },

  { id:'gen-m-def', caseNumber:2, caseLabel:'2격 · Genitiv(소유격)', sentence:'Das Auto ___ Mannes ist neu.', choices:['der','den','dem','des'], answer:'des', translation:'그 남자의 자동차는 새것이다.', explanation:'누구의 자동차인지 나타내므로 2격이에요. 남성 정관사 2격은 des이고 Mann에는 -es가 붙어요.' },
  { id:'gen-f-def', caseNumber:2, caseLabel:'2격 · Genitiv(소유격)', sentence:'Die Tasche ___ Frau ist rot.', choices:['die','der','den','dem'], answer:'der', translation:'그 여자의 가방은 빨간색이다.', explanation:'누구의 가방인지 나타내므로 2격이에요. 여성 정관사 2격은 der예요.' },
  { id:'gen-n-def', caseNumber:2, caseLabel:'2격 · Genitiv(소유격)', sentence:'Das Spielzeug ___ Kindes liegt hier.', choices:['das','des','dem','den'], answer:'des', translation:'그 아이의 장난감이 여기에 있다.', explanation:'누구의 장난감인지 나타내므로 2격이에요. 중성 정관사 2격은 des이고 Kind에는 -es가 붙어요.' },
  { id:'gen-pl-def', caseNumber:2, caseLabel:'2격 · Genitiv(소유격)', sentence:'Die Eltern ___ Kinder arbeiten.', choices:['die','der','den','des'], answer:'der', translation:'그 아이들의 부모님은 일한다.', explanation:'누구의 부모님인지 나타내므로 2격이에요. 복수 정관사 2격은 der예요.' },
  { id:'gen-m-indef', caseNumber:2, caseLabel:'2격 · Genitiv(소유격)', sentence:'Das ist der Name ___ Freundes.', choices:['ein','einen','einem','eines'], answer:'eines', translation:'이것은 한 친구의 이름이다.', explanation:'누구의 이름인지 나타내므로 2격이에요. 남성 부정관사 2격은 eines예요.' },
  { id:'gen-f-indef', caseNumber:2, caseLabel:'2격 · Genitiv(소유격)', sentence:'Die Farbe ___ Tasche gefällt mir.', choices:['eine','einer','einen','einem'], answer:'einer', translation:'한 가방의 색이 내 마음에 든다.', explanation:'어느 가방의 색인지 나타내므로 2격이에요. 여성 부정관사 2격은 einer예요.' },

  { id:'dat-m-help', caseNumber:3, caseLabel:'3격 · Dativ(여격)', sentence:'Ich helfe ___ Mann.', choices:['der','den','dem','des'], answer:'dem', translation:'나는 그 남자를 돕는다.', explanation:'helfen은 도움을 받는 사람을 3격으로 써요. 남성 정관사 3격은 dem이에요.' },
  { id:'dat-f-thank', caseNumber:3, caseLabel:'3격 · Dativ(여격)', sentence:'Wir danken ___ Frau.', choices:['die','der','den','dem'], answer:'der', translation:'우리는 그 여자에게 감사한다.', explanation:'danken은 감사의 대상을 3격으로 써요. 여성 정관사 3격은 der예요.' },
  { id:'dat-n-belong', caseNumber:3, caseLabel:'3격 · Dativ(여격)', sentence:'Das Buch gehört ___ Kind.', choices:['das','des','dem','den'], answer:'dem', translation:'그 책은 그 아이의 것이다.', explanation:'gehören은 소유자를 3격으로 써요. 중성 정관사 3격은 dem이에요.' },
  { id:'dat-pl-mit', caseNumber:3, caseLabel:'3격 · Dativ(여격)', sentence:'Anna spielt mit ___ Kindern.', choices:['die','der','den','dem'], answer:'den', translation:'안나는 그 아이들과 함께 논다.', explanation:'mit는 항상 3격을 요구해요. 복수는 den Kindern처럼 명사에도 보통 -n이 붙어요.' },
  { id:'dat-n-give', caseNumber:3, caseLabel:'3격 · Dativ(여격)', sentence:'Sie gibt ___ Kind einen Apfel.', choices:['ein','einen','einem','eines'], answer:'einem', translation:'그녀는 한 아이에게 사과 하나를 준다.', explanation:'geben에서 물건을 받는 사람은 3격이에요. 중성 부정관사 3격은 einem이에요.' },
  { id:'dat-pronoun-like', caseNumber:3, caseLabel:'3격 · Dativ(여격)', sentence:'Der Film gefällt ___.', choices:['ich','mich','mir','meiner'], answer:'mir', translation:'그 영화가 내 마음에 든다.', explanation:'gefallen은 마음에 들어 하는 사람을 3격으로 써요. ich의 3격은 mir예요.' },

  { id:'acc-m-see', caseNumber:4, caseLabel:'4격 · Akkusativ(목적격)', sentence:'Ich sehe ___ Mann.', choices:['der','den','dem','des'], answer:'den', translation:'나는 그 남자를 본다.', explanation:'sehen의 직접 목적어는 4격이에요. 남성 정관사 4격은 den이에요.' },
  { id:'acc-f-visit', caseNumber:4, caseLabel:'4격 · Akkusativ(목적격)', sentence:'Wir besuchen ___ Frau.', choices:['die','der','den','dem'], answer:'die', translation:'우리는 그 여자를 방문한다.', explanation:'besuchen의 직접 목적어는 4격이에요. 여성 정관사 4격은 die예요.' },
  { id:'acc-n-need', caseNumber:4, caseLabel:'4격 · Akkusativ(목적격)', sentence:'Er braucht ___ Auto.', choices:['ein','einen','einem','eines'], answer:'ein', translation:'그는 자동차 한 대가 필요하다.', explanation:'brauchen의 직접 목적어는 4격이에요. 중성 부정관사 4격은 1격과 같은 ein이에요.' },
  { id:'acc-f-buy', caseNumber:4, caseLabel:'4격 · Akkusativ(목적격)', sentence:'Sie kauft ___ Tasche.', choices:['eine','einer','einen','einem'], answer:'eine', translation:'그녀는 가방 하나를 산다.', explanation:'kaufen의 직접 목적어는 4격이에요. 여성 부정관사 4격은 eine예요.' },
  { id:'acc-pronoun-see', caseNumber:4, caseLabel:'4격 · Akkusativ(목적격)', sentence:'Ich sehe ___.', choices:['er','ihn','ihm','seiner'], answer:'ihn', translation:'나는 그를 본다.', explanation:'sehen은 목적어를 4격으로 써요. er의 4격은 ihn이에요.' },
  { id:'acc-pronoun-ask', caseNumber:4, caseLabel:'4격 · Akkusativ(목적격)', sentence:'Das Kind fragt ___.', choices:['ich','mich','mir','meiner'], answer:'mich', translation:'그 아이가 나에게 묻는다.', explanation:'fragen은 묻는 대상을 4격으로 써요. ich의 4격은 mich예요.' },
];

export const SUPPLEMENTAL_PRACTICE_WORDS = [
  { id:'practice-aufmachen', german:'aufmachen', korean:'열다', english:'open' },
  { id:'practice-zumachen', german:'zumachen', korean:'닫다', english:'close' },
  { id:'practice-weitermachen', german:'weitermachen', korean:'계속하다', english:'continue' },
  { id:'practice-zurueckkommen', german:'zurückkommen', korean:'돌아오다', english:'come back' },
  { id:'practice-wiederkommen', german:'wiederkommen', korean:'다시 오다', english:'come again' },
  { id:'practice-zurueckfahren', german:'zurückfahren', korean:'차를 타고 돌아가다', english:'travel back' },
  { id:'practice-losfahren', german:'losfahren', korean:'출발하다', english:'set off' },
  { id:'practice-ansehen', german:'ansehen', korean:'바라보다·시청하다', english:'look at/watch' },
  { id:'practice-nachsehen', german:'nachsehen', korean:'확인하다·찾아보다', english:'check/look up' },
  { id:'practice-wiedersehen', german:'wiedersehen', korean:'다시 만나다', english:'see again' },
  { id:'practice-schreiben', german:'schreiben', korean:'쓰다', english:'write' },
  { id:'practice-aufschreiben', german:'aufschreiben', korean:'적어 두다', english:'write down' },
  { id:'practice-beschreiben', german:'beschreiben', korean:'묘사하다', english:'describe' },
  { id:'practice-aussprechen', german:'aussprechen', korean:'발음하다·말로 표현하다', english:'pronounce/express' },
  { id:'practice-besprechen', german:'besprechen', korean:'논의하다', english:'discuss' },
  { id:'practice-versprechen', german:'versprechen', korean:'약속하다', english:'promise' },
  { id:'practice-zuhoeren', german:'zuhören', korean:'귀 기울여 듣다', english:'listen' },
  { id:'practice-ziehen', german:'ziehen', korean:'당기다·이동하다', english:'pull/move' },
  { id:'practice-anziehen', german:'anziehen', korean:'입다', english:'put on' },
  { id:'practice-ausziehen', german:'ausziehen', korean:'벗다·이사 나가다', english:'take off/move out' },
  { id:'practice-vorbereiten', german:'vorbereiten', korean:'준비하다', english:'prepare' },
  { id:'practice-abnehmen', german:'abnehmen', korean:'줄다·살을 빼다', english:'decrease/lose weight' },
  { id:'practice-aufnehmen', german:'aufnehmen', korean:'녹음하다·받아들이다', english:'record/take in' },
  { id:'practice-zurueckgeben', german:'zurückgeben', korean:'돌려주다', english:'give back' },
  { id:'practice-ausgeben', german:'ausgeben', korean:'지출하다·나눠 주다', english:'spend/hand out' },
  { id:'practice-zurueckbringen', german:'zurückbringen', korean:'돌려 가져다주다', english:'bring back' },
  { id:'practice-laden', german:'laden', korean:'싣다·충전하다', english:'load/charge' },
  { id:'practice-herunterladen', german:'herunterladen', korean:'다운로드하다', english:'download' },
  { id:'practice-warm', german:'warm', korean:'따뜻한', english:'warm' },
  { id:'practice-kalt', german:'kalt', korean:'차가운', english:'cold' },
  { id:'practice-offen', german:'offen', korean:'열린', english:'open' },
  { id:'practice-frueh', german:'früh', korean:'이른', english:'early' },
  { id:'practice-dunkel', german:'dunkel', korean:'어두운', english:'dark' },
  { id:'practice-voll', german:'voll', korean:'가득 찬', english:'full' },
  { id:'practice-leer', german:'leer', korean:'빈', english:'empty' },
  { id:'practice-sauber', german:'sauber', korean:'깨끗한', english:'clean' },
  { id:'practice-schmutzig', german:'schmutzig', korean:'더러운', english:'dirty' },
  { id:'practice-stark', german:'stark', korean:'강한', english:'strong' },
  { id:'practice-schwach', german:'schwach', korean:'약한', english:'weak' },
  { id:'practice-gebraucht', german:'gebraucht', korean:'중고의·사용된', english:'used' },
  { id:'practice-nah', german:'nah', korean:'가까운', english:'near' },
  { id:'practice-weit', german:'weit', korean:'먼', english:'far' },
  { id:'practice-innen', german:'innen', korean:'안쪽에', english:'inside' },
  { id:'practice-aussen', german:'außen', korean:'바깥쪽에', english:'outside' },
  { id:'practice-trocken', german:'trocken', korean:'마른', english:'dry' },
  { id:'practice-nass', german:'nass', korean:'젖은', english:'wet' },
  { id:'practice-gesund', german:'gesund', korean:'건강한', english:'healthy' },
  { id:'practice-reich', german:'reich', korean:'부유한', english:'rich' },
  { id:'practice-arm', german:'arm', korean:'가난한', english:'poor' },
  { id:'practice-interessant', german:'interessant', korean:'흥미로운', english:'interesting' },
  { id:'practice-langweilig', german:'langweilig', korean:'지루한', english:'boring' },
  { id:'practice-freundlich', german:'freundlich', korean:'친절한', english:'friendly' },
  { id:'practice-unfreundlich', german:'unfreundlich', korean:'불친절한', english:'unfriendly' },
  { id:'practice-traurig', german:'traurig', korean:'슬픈', english:'sad' },
  { id:'practice-sicher', german:'sicher', korean:'안전한', english:'safe' },
  { id:'practice-gefaehrlich', german:'gefährlich', korean:'위험한', english:'dangerous' },
];

export const ROOT_FAMILIES = [
  { id:'kommen', label:'kommen 계열', root:'kommen', words:['kommen','ankommen','bekommen','mitkommen','zurückkommen','wiederkommen'] },
  { id:'machen', label:'machen 계열', root:'machen', words:['machen','anmachen','ausmachen','mitmachen','aufmachen','zumachen','weitermachen'] },
  { id:'fahren', label:'fahren 계열', root:'fahren', words:['fahren','abfahren','Rad fahren','zurückfahren','losfahren'] },
  { id:'kaufen', label:'kaufen 계열', root:'kaufen', words:['kaufen','einkaufen','verkaufen'] },
  { id:'sehen', label:'sehen 계열', root:'sehen', words:['sehen','aussehen','fernsehen','ansehen','nachsehen','wiedersehen'] },
  { id:'stehen', label:'stehen 계열', root:'stehen', words:['stehen','aufstehen','verstehen'] },
  { id:'holen', label:'holen 계열', root:'holen', words:['holen','abholen','wiederholen'] },
  { id:'bringen', label:'bringen 계열', root:'bringen', words:['bringen','mitbringen','zurückbringen'] },
  { id:'nehmen', label:'nehmen 계열', root:'nehmen', words:['nehmen','mitnehmen','abnehmen','aufnehmen'] },
  { id:'geben', label:'geben 계열', root:'geben', words:['geben','abgeben','ausgeben','zurückgeben'] },
  { id:'schreiben', label:'schreiben 계열', root:'schreiben', words:['schreiben','aufschreiben','unterschreiben','beschreiben'] },
  { id:'sprechen', label:'sprechen 계열', root:'sprechen', words:['sprechen','aussprechen','besprechen','versprechen'] },
  { id:'hoeren', label:'hören 계열', root:'hören', words:['hören','aufhören','zuhören'] },
  { id:'ziehen', label:'ziehen 계열', root:'ziehen', words:['ziehen','anziehen','ausziehen','umziehen'] },
  { id:'stellen', label:'stellen 계열', root:'stellen', words:['stellen','(sich) vorstellen','bestellen'] },
  { id:'laden', label:'laden 계열', root:'laden', words:['laden','einladen','herunterladen'] },
];

export const TOPIC_GROUPS = [
  { id:'transport', label:'교통·이동', icon:'🚆', words:['die Bahn','der Bahnhof','der Bus, -se','das Auto, -s','das Fahrrad, -ä, er','das Taxi, -s','der Flughafen','das Flugzeug','die Haltestelle','die Straßenbahn','der Zug, -ü, e','das Ticket, -s','fahren','fliegen'] },
  { id:'body-health', label:'신체·건강', icon:'🩺', words:['das Auge, -n','der Bauch','der Fuß, -ü, e','die Hand, -ä, e','das Haar, -e','der Kopf','der Mund','der Arzt, -Ä, e','der Doktor','die Praxis','das Fieber','weh tun','krank'] },
  { id:'food', label:'음식·음료', icon:'🍎', words:['das Essen','essen','trinken','das Brot, -e','das Brötchen, –','die Milch','der Kaffee','das Wasser','die Kartoffel, -n','die Bäckerei','der Hunger','das Lokal'] },
  { id:'family', label:'가족·사람', icon:'👨‍👩‍👧', words:['die Familie, -n','die Eltern (pl.)','die Mutter, -ü','der Vater, -ä','der Bruder, -ü','die Schwester, -n','die Geschwister (pl.)','das Kind, -er','der Sohn, -ö, e','die Tochter, -ö','die Großeltern (pl.)','der Partner, -/ die Partnerin, -nen'] },
  { id:'home', label:'집·생활', icon:'🏠', words:['das Haus, -ä, er','die Wohnung, -en','das Zimmer, –','die Küche','das Bett, -en','der Raum, -ä, e','der Tisch, -e','der Herd','der Balkon','das Bad','die Dusche','die Toilette, -en','der Schrank, -ä, e','das Sofa'] },
  { id:'school-work', label:'학교·직업', icon:'📚', words:['die Schule','der Unterricht','die Stunde, -n','der Lehrer, –','der Schüler, –','der Student, -en','der Beruf, -e','der Job, -s','der Arbeitsplatz, -ä, e','die Firma','arbeiten','lernen'] },
  { id:'travel', label:'여행·숙박', icon:'🧳', words:['reisen','die Reise','das Reisebüro, -s','der Reiseführer','der Urlaub','der Pass, -ä, e','das Gepäck','der Koffer, –','das Hotel, -s','der Gast, -ä, e','das Doppelzimmer','das Einzelzimmer'] },
  { id:'communication', label:'통신·우편·미디어', icon:'📱', words:['anrufen','der Anruf, -e','telefonieren','das Telefon','das Handy, -s','die Post','der Brief, -e','die E-Mail, -s','das Internet','die Zeitung, -en','fernsehen'] },
  { id:'shopping', label:'쇼핑·돈', icon:'🛍️', words:['einkaufen','kaufen','verkaufen','der Preis, -e','das Geld','bar','die Bank','die Kasse','(Kredit)-Karte, -n','kosten','bezahlen','zahlen'] },
];

export const ANTONYM_PAIRS = [
  { id:'big-small', prompts:['크다','작다'], words:['groß','klein'] },
  { id:'old-young', prompts:['나이 들다','젊다'], words:['alt','jung'] },
  { id:'good-bad', prompts:['좋다','나쁘다'], words:['gut','schlecht'] },
  { id:'right-wrong', prompts:['맞다','틀리다'], words:['richtig','falsch'] },
  { id:'many-few', prompts:['많다','적다'], words:['viel','wenig'] },
  { id:'fast-slow', prompts:['빠르다','느리다'], words:['schnell','langsam'] },
  { id:'left-right', prompts:['왼쪽','오른쪽'], words:['links','rechts'] },
  { id:'up-down', prompts:['위','아래'], words:['oben','unten'] },
  { id:'expensive-cheap', prompts:['비싸다','저렴하다'], words:['teuer','günstig'] },
  { id:'loud-quiet', prompts:['시끄럽다','조용하다'], words:['laut','leise'] },
  { id:'long-short', prompts:['길다','짧다'], words:['lang','kurz'] },
  { id:'easy-hard', prompts:['쉽다·가볍다','어렵다·무겁다'], words:['leicht','schwer'] },
  { id:'male-female', prompts:['남성','여성'], words:['männlich','weiblich'] },
  { id:'alone-together', prompts:['혼자','함께'], words:['allein','zusammen'] },
  { id:'yes-no', prompts:['네','아니요'], words:['ja','nein'] },
  { id:'warm-cold', prompts:['따뜻하다','차갑다'], words:['warm','kalt'] },
  { id:'open-closed', prompts:['열려 있다','닫혀 있다'], words:['offen','geschlossen'] },
  { id:'early-late', prompts:['이르다','늦다'], words:['früh','spät'] },
  { id:'bright-dark', prompts:['밝다','어둡다'], words:['hell','dunkel'] },
  { id:'full-empty', prompts:['가득 차다','비어 있다'], words:['voll','leer'] },
  { id:'clean-dirty', prompts:['깨끗하다','더럽다'], words:['sauber','schmutzig'] },
  { id:'strong-weak', prompts:['강하다','약하다'], words:['stark','schwach'] },
  { id:'new-used', prompts:['새것이다','중고다'], words:['neu','gebraucht'] },
  { id:'near-far', prompts:['가깝다','멀다'], words:['nah','weit'] },
  { id:'inside-outside', prompts:['안쪽','바깥쪽'], words:['innen','außen'] },
  { id:'dry-wet', prompts:['마르다','젖다'], words:['trocken','nass'] },
  { id:'healthy-sick', prompts:['건강하다','아프다'], words:['gesund','krank'] },
  { id:'rich-poor', prompts:['부유하다','가난하다'], words:['reich','arm'] },
  { id:'interesting-boring', prompts:['흥미롭다','지루하다'], words:['interessant','langweilig'] },
  { id:'friendly-unfriendly', prompts:['친절하다','불친절하다'], words:['freundlich','unfreundlich'] },
  { id:'happy-sad', prompts:['행복하다','슬프다'], words:['glücklich','traurig'] },
  { id:'free-occupied', prompts:['비어 있다','사용 중이다'], words:['frei','besetzt'] },
  { id:'safe-dangerous', prompts:['안전하다','위험하다'], words:['sicher','gefährlich'] },
];

export const PREFIX_CARDS = [
  { prefix:'ab-', meaning:'떨어져 나감·출발', note:'어떤 지점에서 멀어지거나 떼어 내는 느낌을 더해요.', examples:['abfahren','abholen','abgeben'] },
  { prefix:'an-', meaning:'접근·시작·접촉', note:'무언가에 가까이 가거나 동작을 시작하는 느낌을 더해요.', examples:['ankommen','anmachen','anrufen'] },
  { prefix:'auf-', meaning:'위로·열림 (단어별 의미 변화)', note:'aufstehen은 위로 일어나는 느낌이지만, aufhören처럼 완성된 뜻을 따로 외워야 하는 단어도 있어요.', examples:['aufstehen','aufhören'], extraExamples:[{german:'aufmachen',korean:'열다',english:'open'}] },
  { prefix:'aus-', meaning:'밖으로·완료·꺼짐', note:'안에서 밖으로 나가거나 동작이 끝나는 느낌을 더할 수 있지만, 완성된 뜻은 단어별로 확인해요.', examples:['aussehen','ausmachen','ausfüllen'], extraExamples:[{german:'auskommen',korean:'잘 지내다/충분하다',english:'get along/manage/be sufficient'}] },
  { prefix:'ein-', meaning:'안으로·진입', note:'밖에서 안으로 들어가거나 어떤 활동에 진입하는 느낌이 자주 나타나요.', examples:['einkaufen','einsteigen'] },
  { prefix:'mit-', meaning:'함께·동반', note:'다른 사람이나 물건과 함께 움직이는 뜻을 더해요.', examples:['mitkommen','mitmachen','mitbringen','mitnehmen'] },
  { prefix:'vor-', meaning:'앞·이전·미리', note:'공간적으로 앞이거나 시간적으로 먼저라는 느낌을 더해요.', examples:['(sich) vorstellen','der Vorname, -n','die Vorwahl'], extraExamples:[{german:'vorbereiten',korean:'준비하다',english:'prepare'}] },
  { prefix:'zurück-', meaning:'뒤로·되돌아감', note:'원래 위치나 이전 상태로 돌아가는 뜻을 더해요.', examples:[], extraExamples:[{german:'zurückkommen',korean:'돌아오다',english:'come back'},{german:'zurückfahren',korean:'돌아가다',english:'travel/drive back'}] },
  { prefix:'zu-', meaning:'닫힘·~쪽으로', note:'닫히는 움직임이나 어떤 대상을 향하는 느낌을 나타낼 수 있어요.', examples:[], extraExamples:[{german:'zumachen',korean:'닫다',english:'close'},{german:'zuhören',korean:'귀 기울여 듣다',english:'listen'}] },
  { prefix:'be-', meaning:'대상에 작용·타동화', note:'분리되지 않는 접두사예요. 뜻을 단순 합산하기 어려운 단어도 많아요.', examples:['bekommen','bezahlen','besuchen'] },
  { prefix:'ver-', meaning:'변화·결과·잘못', note:'분리되지 않으며 의미가 다양해요. 각 단어의 완성된 뜻으로 익혀요.', examples:['verkaufen','verstehen','verdienen'] },
  { prefix:'wieder-', meaning:'다시·반복', note:'이미 한 동작을 다시 한다는 뜻을 더해요.', examples:['wiederholen','das Wiedersehen','das Wiederhören'], extraExamples:[{german:'wiederkommen',korean:'다시 오다',english:'come again'}] },
];
